# Loads default set of integrations. Do not remove.

config:
counter:
dhcp:
frontend:
map:
my:
sun:
script:
ssdp:
tag:
timer:
usb:
webhook:
zeroconf:
zone:

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      allow_bypass_login: true
    - type: homeassistant
