# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      allow_bypass_login: true
    - type: homeassistant
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
