name: Build anycubic-python 🐍 distributions

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ 'pypy-3.7', 'pypy-3.8', 'pypy-3.9' ]
    name: Build Python 🐍 ${{ matrix.python-version }} 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Set up Python
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: >-
        python -m
        pip install
        build
        --user
        
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-18.04
    name: Publish distribution 📦 to PyPI
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Set up Python
      with:
        python-version: pypy-3.9
        architecture: x64
    - run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - name: Publish  
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
