name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 'pypy-3.7', 'pypy-3.8', 'pypy-3.9' ]
    name: Build and publish Python 🐍 ${{ matrix.python-version }} distributions 📦 to PyPI and TestPyPI
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Set up Python
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: >-
        python -m
        pip install
        build
        --user
  package:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
  publish:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    name: Publish distribution 📦 to PyPI
    needs: setup
    steps:
    - name: Publish  
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
