name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    
    name: setup items. for Python  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Set up Python
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
  build:
    strategy:
      matrix:
        python-version: [ 'pypy-3.7', 'pypy-3.8', 'pypy-3.9' ]
    name: build python 🐍${{ matrix.python-version }} 
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: >-
        python -m
        pip install
        build
        --user
  package:
    name: create distributions 📦
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - name: Publish distributions 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
